### PR TITLE
chore: update dependencies

### LINKED ISSUE #42: improve dev tools
**Please describe the feature**

As a developer, I want to use more modern dev tools so that I can integrate new (versions of) libraries and have better developer experience.

**Describe the solution you would like**

Modern dev tools that uses more recent versions of ECMAScript (JavaScript standard) that plays well with libraries that require ES6.

The work for this issue should include the following:

1. Research modern dev tools suitable for this repo.
2. Make the changes in codebase to switch to the new tool(s).
3. Make sure that the https://github.com/MetabolicAtlas/3d-network-viewer/pull/40 PR does not break the project.

**Additional context**

A recent dependabot PR breaks the project because the proposed version uses ES6, which is currently not supported by this repo's dev tools. More discussion around this issue can be found at: https://github.com/MetabolicAtlas/3d-network-viewer/pull/40#issuecomment-1026894216.

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #42.

**Type of change**  

- [x] Other
 
**List of changes made**  

- Upgrade major version for `rollup`
- Upgrade minor version of other dependencies (`npm update`)

**Testing**  

- A rebuild is needed due to new dependencies
- Instructions on how to test

Install new dependencies (`npm install`) and verify that both the dev and build commands work `npm run watch` + `npm run start`, and `npm run prepare`.

**Further comments**  

The output of `npm run prepare` is exactly the same as the one before changes in this PR. Therefore no version bump (for this library) is needed.

The previous PRs #52 (eslint, prettier, and git hooks) and #60 (esm output instead of umd) have also contributed to this issue.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by nanjiangshu — COMMENTED** [review]
It works well when I followed all testing instructions. But I'm not quite sure if this updating resolved the original issue description:
```
Modern dev tools that uses more recent versions of ECMAScript (JavaScript standard) that plays well with libraries that require ES6.
```

**Comment by e0** [comment]
> It works well when I followed all testing instructions. But I'm not quite sure if this updating resolved the original issue description:
> 
> ```
> Modern dev tools that uses more recent versions of ECMAScript (JavaScript standard) that plays well with libraries that require ES6.
> ```

These have been handled in the previous PRs #52 and #60.

**Comment by nanjiangshu** [comment]
> > ```
> > 
> > ```
> 
> 
> These have been handled in the previous PRs #52 and #60.

Aha, I see. Thanks for pointing it out.

**Review by nanjiangshu — APPROVED** [review]
LGTM!

**Review by inghylt — APPROVED** [review]
LGTM!

**Pull request merged**
