### PR TITLE
chore: linter and formatter

### LINKED ISSUE #34: add linter integration for the 3D-network-viewer
As a developer, I want to rely on a linter, so that I can worry less, if at all, about the quality of the code formatting.

**Acceptance criteria**
- [ ] GH Action using linter
- [ ] passing all linter checks

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #34.

**Type of change**  

- [x] Other
 
**List of changes made**  

- Add `eslint` and `prettier` to the project.
- Format code and modernize (replace `vars` and use arrow functions where appropriate) `public/index.html`.
- Add local git commit hooks including instructions in `README.md`.
- Add GitHub actions.

**Testing**  

##### CLI
1. Install new dependencies: `npm install`.
2. Check formatting using `prettier`: `npm run check-format`.
3. Fix formatting using `prettier`: `npm run format`.
4. Run `eslint`: `npm run lint`.
5. Try to change some files and add some formatting and linting errors and run step 2-4 again. Verify that errors are shown and/or fixed.

##### Commit hooks
1. Setup the commit hooks: `git config core.hooksPath git_hooks`.
2. Try to change some files and add some formatting and linting errors.
3. Try to commit the code. Verify that lint errors prevent the commit and formatting issues are auto-fixed.

##### GitHub actions
1. Try to change some files and add some formatting and linting errors.
2. Bypass the commit hooks and commit the code : `git commit --no-verify ...`
3. Checkout a new branch locally and push it to GitHub. Verify that lint errors are caught and formatting issues are auto-fixed (with a new commit).
4. Delete the branch.

**Further comments**  

This work is largely based on the previous work with `eslint` and `prettier` in the MetabolicAtlas repo.

**Definition of Done checklist**  
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by MalinAhlberg — APPROVED** [review]
Well done!

**Comment by mihai-sysbio** [comment]
Some parts under the `Testing` header in the original post should also go somewhere else: in the README of this repo, or in (missing as of now) `CONTRIBUTORS.md`, or in the `dev-docs/wiki`. Please decide the most appropriate place, and create the corresponding issue if needed.

**Comment by e0** [comment]
> Some parts under the `Testing` header in the original post should also go somewhere else: in the README of this repo, or in (missing as of now) `CONTRIBUTORS.md`, or in the `dev-docs/wiki`. Please decide the most appropriate place, and create the corresponding issue if needed.

Imo the only part that should be added is about the local git commit hooks since setting that up would ensure both `eslint` and `prettier` are run whenever code is committed. This was already added to `README.md` in [this commit](https://github.com/MetabolicAtlas/3d-network-viewer/pull/52/commits/2f57ffe63b81cfe8f6516b1ab84fe221e53bd237).  @mihai-sysbio is there any other part that you think should be added?

**Review by inghylt — APPROVED** [review]
Nice work!

**Comment by mihai-sysbio** [comment]
@e0 I somehow missed the README, where I could have provided suggestions. Instead of referring to linting and formatting, I could have imagined adding a clearer link to the commands in `package.json`.

> * Check formatting using `prettier`: `npm run check-format`.
> * Fix formatting using `prettier`: `npm run format`.
> * Run `eslint`: `npm run lint`.

This also make it apparent that the use of prettier in the git hook is different, i.e. not using the npm command.

**Pull request merged**
