### PR TITLE
feat: prevent mouse events when cursor is outside

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR is related to https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1172.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
 
**List of changes made**  

Short circuit mouse (move and click) event handlers if the cursor is outside the container.

**Testing**  

- A certain branch in other repos is needed
- A rebuild is needed due to new dependencies
- Relative urls that can be reused both for production and local testing
- Instructions on how to test

For real world use, it is best to test this branch using the [MetabolicAtlas repo](https://github.com/MetabolicAtlas/MetabolicAtlas).

- To use it, do:
1. Change value for dependency from version number to git branch in `frontend/package.json`.
```json
    "@metabolicatlas/3d-network-viewer": "MetabolicAtlas/3d-network-viewer#fix/events-outside-container",
```

2.  Install the dependency and build it.
```bash
docker-compose --env-file env-local.env -f docker-compose.yml -f docker-compose-local.yml up -d --no-deps --build frontend
ma-exec frontend npm --prefix node_modules/@metabolicatlas/3d-network-viewer/ install
ma-exec frontend npm --prefix node_modules/@metabolicatlas/3d-network-viewer/ run build
```
3. Visit `/explore/Human-GEM/interaction-partners/MAM02040r?expandedIds=&dataTypes=transcriptomics&dataSources=hpaRna.tsv&dataSets=None`.
4. Move mouse around outside of the container, e.g. around the reactions table, where there should be nodes. Verify that no labels are displayed.
5. Visit `/explore/Human-GEM/map-viewer/golgi_apparatus?dim=3d&panel=0&sel=&search=&coords=-4370.88,-32523.99,0.11,-8.42,72.46,148.15&dataTypes=None&dataSources=None&dataSets=None`
6. Move mouse around outside of the container, e.g. around the map listing sidebar, where there should be nodes. Verify that no labels are displayed.

**Further comments**  

If this seems to work well. I can add a version bump commit and create an accompanying PR in the main repo.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by MalinAhlberg — APPROVED** [review]
Elegant solution, works well :star:

**Comment by MalinAhlberg** [comment]
Oh, just noted that I cannot click nodes on the 3d maps with this PR when using a mobile device, which is possible in v0.1.29. Would be nice if someone else could verify this!

**Comment by nanjiangshu** [comment]
> Oh, just noted that I cannot click nodes on the 3d maps with this PR when using a mobile device, which is possible in v0.1.29. Would be nice if someone else could verify this!

@MalinAhlberg You probably need to click the icon `Enable touch simulation` (forefinger) so that you can click the nodes

**Comment by e0** [comment]
> > Oh, just noted that I cannot click nodes on the 3d maps with this PR when using a mobile device, which is possible in v0.1.29. Would be nice if someone else could verify this!
> 
> @MalinAhlberg You probably need to click the icon `Enable touch simulation` (forefinger) so that you can click the nodes

For me it works regardless of if `Enable touch simulation` is on or off. @MalinAhlberg did you try this with an actual mobile device as opposed to a simulator?

**Comment by MalinAhlberg** [comment]
> > > Oh, just noted that I cannot click nodes on the 3d maps with this PR when using a mobile device, which is possible in v0.1.29. Would be nice if someone else could verify this!
> > 
> > 
> > @MalinAhlberg You probably need to click the icon `Enable touch simulation` (forefinger) so that you can click the nodes
> 
> For me it works regardless of if `Enable touch simulation` is on or off. @MalinAhlberg did you try this with an actual mobile device as opposed to a simulator?

Yes, it usually works for me without having to enabling touch simulation. I only tried this on chrome's simulator, so not sure it would happen on an actual mobile device. (If we deploy this to dev, I could try, but I'm not sure how to do that using a branch of this repo.) On firefox, it works for me, so if it works for you guys as well, then maybe it's just chrome's simulator being annoying.

**Comment by e0** [comment]
@MalinAhlberg it works in both Safari and Firefox simulators for me. I think we can merge this for now and try to do a deploy after https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1223 gets merged as well. We can open up a new issue if needed.

**Pull request merged**
