### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  

This PR closes #44, #45, #46, #47, #50, and is related to #48.

**Type of change**  

- [x] Other
 
**List of changes made**  

- Update project dependencies (`npm update`)

**Testing**  

1. Install newer versions of dependencies: `npm install`.
2. Verify that the development runs: `npm start` and that the network loads as expected in the browser. Please also verify that there are no console errors.
3. Verify that the project can build without any problems: `npm run build`.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MalinAhlberg** [comment]
Nice work! Everything still works, as far as I can tell. But when installing, I still get `2 moderate severity vulnerabilities`. Should those be fixed in this PR?

**Comment by inghylt** [comment]
Everything works well! Agree with @MalinAhlberg, it would be nice to fix everything reported while we are at it. I tried updating serve to version 14.0.1 which was the only vulnerability reported for me and that didn't break anything so I think it would be straighforward to do

**Comment by nanjiangshu** [comment]
All work well when I tried. I agree it will be great to fix also `ajv` and `serve` if it is straightforward to do.

**Comment by e0** [comment]
Thank you for catching the warning messages! That was sloppy of me. I have [updated major versions for some dependencies](https://github.com/MetabolicAtlas/3d-network-viewer/pull/49/commits/9912a5dfd4e4d9457ee0fa4aed2cdfff18a84ce4) now.

**Review by nanjiangshu — APPROVED** [review]
👍

**Review by MalinAhlberg — APPROVED** [review]
:v:

**Comment by mihai-sysbio** [comment]
I can also confirm that the performance of the viewer has remained as high as before.

**Pull request merged**
